"use strict";

// Seed content for the PanPals demo. Loaded before app.js, which copies it
// into localStorage on first visit (timestamps are materialized from
// minutesAgo at seed time).
//
// Special users:
//   - "you"  — the prebaked profile you start on (a pan, naturally)
//   - "vexx" — the founder. Everyone is friends with Vexx, MySpace-Tom style.
const SEED = {
  users: [
    {
      id: "you",
      name: "Pat the Pan",
      firstName: "Pat",
      handle: "panpat",
      emoji: "🍳",
      color: "#e0762e",
      type: "All-Purpose Frying Pan",
      bio: "Fresh out of the box. Nonstick, non-judgmental, ready to make pals.",
      followers: 1,
      following: 1,
      isYou: true,
    },
    {
      id: "vexx",
      name: "Vexx WereWolf",
      firstName: "Vexx",
      handle: "vexxwerewolf",
      emoji: "🐺",
      color: "#5b4a78",
      type: "Founder of PanPals",
      badge: "🌕 Founder",
      bio: "Everyone's first pal — yes, even the gravy boat's. I howl at every full plate.",
      followers: 2400000,
      following: 2400000,
      isFounder: true,
    },
    {
      id: "carl",
      name: "Cast Iron Carl",
      handle: "castironcarl",
      emoji: "🍳",
      color: "#3f3a36",
      type: "Cast Iron Skillet",
      bio: "Seasoned since 1987. Low and slow is a lifestyle. Soap is a slur.",
      followers: 48200,
      following: 8,
    },
    {
      id: "fiona",
      name: "Fine China Fiona",
      handle: "finechinafiona",
      emoji: "🍽️",
      color: "#7c93c4",
      type: "Bone China Dinner Set",
      bio: "Hand wash only. Special occasions only. Emotionally available twice a year.",
      followers: 31400,
      following: 12,
    },
    {
      id: "nancy",
      name: "Nonstick Nancy",
      handle: "nonsticknancy",
      emoji: "🥞",
      color: "#d2738a",
      type: "Nonstick Frying Pan",
      bio: "Nothing sticks to me — especially drama. Wooden spoons only, please.",
      followers: 23100,
      following: 45,
    },
    {
      id: "wendy",
      name: "Wok Wendy",
      handle: "wokwendy",
      emoji: "🥘",
      color: "#b3541e",
      type: "Carbon Steel Wok",
      bio: "High heat, fast friends. Professional vegetable tosser.",
      followers: 18700,
      following: 64,
    },
    {
      id: "tina",
      name: "Teacup Tina",
      handle: "teacuptina",
      emoji: "🍵",
      color: "#4e8d7c",
      type: "Porcelain Teacup",
      bio: "Storm in progress. I hold exactly one serving of opinions at a time.",
      followers: 12900,
      following: 203,
    },
    {
      id: "colin",
      name: "Colander Colin",
      handle: "colandercolin",
      emoji: "🍝",
      color: "#8a9a5b",
      type: "Stainless Colander",
      bio: "I have a lot of holes in my arguments. It's by design.",
      followers: 9800,
      following: 87,
    },
    {
      id: "gary",
      name: "Gravy Boat Gary",
      handle: "gravyboatgary",
      emoji: "⛵",
      color: "#8c6239",
      type: "Ceramic Gravy Boat",
      bio: "Sailing the seas of Sunday roast. Seasonal worker, year-round dreamer.",
      followers: 8400,
      following: 19,
    },
    {
      id: "sam",
      name: "Saucepan Sam",
      handle: "saucepansam",
      emoji: "🍲",
      color: "#c98a2d",
      type: "Stainless Saucepan",
      bio: "Simmering thoughts daily. Patience makes the sauce.",
      followers: 7600,
      following: 31,
    },
  ],

  posts: [
    {
      id: "seed-1",
      userId: "you",
      minutesAgo: 3,
      text: "Hi everyone! Fresh out of the box and ready to sizzle. Vexx friended me before I even finished signing up?? Nicest werewolf I've ever met. #NewPan #DayOne",
      sears: 7,
      comments: [
        { userId: "vexx", minutesAgo: 2, text: "Welcome to the family, Pat! Howl if you need anything. 🌕" },
        { userId: "nancy", minutesAgo: 1, text: "Welcome bb! Pro tip: never let them stack you." },
      ],
    },
    {
      id: "seed-2",
      userId: "vexx",
      minutesAgo: 5,
      pinned: true,
      text: "Welcome to PanPals, @panpat! 🌕 I'm Vexx — everyone's first pal here. Don't mind the fur in the cutlery drawer. Make yourself at home. #Welcome #FirstPal",
      sears: 1042,
      comments: [
        { userId: "gary", minutesAgo: 4, text: "He friended me before I was even glazed. A gentleman." },
      ],
    },
    {
      id: "seed-3",
      userId: "tina",
      minutesAgo: 8,
      text: "About to spill some EXTREMELY hot tea about what the microwave said to the mug last night. Thread incoming. 🫖 #SpillingTheTea",
      sears: 23,
      comments: [
        { userId: "gary", minutesAgo: 3, text: "Pour it. Slowly. Like gravy." },
      ],
    },
    {
      id: "seed-4",
      userId: "nancy",
      minutesAgo: 27,
      text: "PSA: metal utensils are a form of violence. Wooden spoons or we're done. 💅 #NonstickLife #TeflonTalk",
      sears: 89,
      comments: [
        { userId: "carl", minutesAgo: 20, text: "Try being scrubbed with steel wool for thirty years and then talk to me about trauma." },
      ],
    },
    {
      id: "seed-5",
      userId: "carl",
      minutesAgo: 65,
      text: "Someone in this house washed me WITH SOAP. Thirty-seven years of seasoning. Gone. I am unrecognizable to myself. #CastIronCare #NeverForget",
      sears: 412,
      comments: [
        { userId: "wendy", minutesAgo: 50, text: "Stay strong Carl. Re-season and rise. 🔥" },
        { userId: "fiona", minutesAgo: 41, text: "I simply cannot imagine being washed more than twice a year." },
      ],
    },
    {
      id: "seed-6",
      userId: "gary",
      minutesAgo: 130,
      text: "They only take me out of the cabinet twice a year, but I refuse to be bitter. I'm savory. #GravyGang #HolidayCrew",
      sears: 156,
      comments: [
        { userId: "tina", minutesAgo: 110, text: "Twice?? Look at Mr. Popular over here." },
      ],
    },
    {
      id: "seed-7",
      userId: "wendy",
      minutesAgo: 190,
      text: "Got tossed 47 times during dinner service and didn't lose a single snap pea. Core strength, people. #WokThisWay #HighHeatHighStandards",
      sears: 203,
      comments: [],
    },
    {
      id: "seed-8",
      userId: "colin",
      minutesAgo: 300,
      text: "My therapist says I let too many things slip through. I told her that is literally my entire job description. #Drained #HoleisticHealing",
      sears: 178,
      comments: [
        { userId: "sam", minutesAgo: 280, text: "You cannot keep making this joke every week." },
        { userId: "colin", minutesAgo: 275, text: "Watch me." },
      ],
    },
    {
      id: "seed-9",
      userId: "fiona",
      minutesAgo: 420,
      text: "Got taken out of the cabinet for a Tuesday dinner. A TUESDAY. Is nothing sacred anymore?? #FineChinaProblems",
      sears: 96,
      comments: [
        { userId: "nancy", minutesAgo: 400, text: "Girl, some of us work every single day." },
      ],
    },
    {
      id: "seed-10",
      userId: "sam",
      minutesAgo: 540,
      text: "Simmer down everyone, it's reduction season. Patience makes the sauce. #SauceLife #SlowAndSteady",
      sears: 64,
      comments: [],
    },
    {
      id: "seed-11",
      userId: "vexx",
      minutesAgo: 720,
      text: "Reminder from your first pal: hand-wash your friendships and your fine china — both crack under pressure. 🌕 #VexxWisdom",
      sears: 999,
      comments: [
        { userId: "fiona", minutesAgo: 700, text: "Finally, someone who understands me." },
      ],
    },
    {
      id: "seed-12",
      userId: "carl",
      minutesAgo: 1560,
      text: "Daily reminder: low and slow. In cooking and in life. #CastIronCare #SkilletWisdom",
      sears: 251,
      comments: [
        { userId: "tina", minutesAgo: 1500, text: "Needed this today 🍵" },
      ],
    },
  ],
};
